apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-product-config
data:
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-product
  labels:
    app: crud-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-product
  template:
    metadata:
      labels:
        app: crud-product
    spec:
      containers:
        - name: crud-product
          image: farinojl/crud-product:v1.1.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: crud-product-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: crud-product
spec:
  selector:
    app: crud-product
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30008
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crud-product
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-product
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
